django-docker/website_store/mini_app/urls.py
from django.urls import path
from mini_app.views import (ArticleView, MainMenuView, ProductCardView,
                            SearchView, TestTemplateView, test_view)

app_name = 'mini_app'

urlpatterns = [
    path('menu/', MainMenuView.as_view() , name='main_menu'),
    path('menu/<str:param>/', MainMenuView.as_view(), name='main_menu_with_param'),
    path('product/<str:product_id>', ProductCardView.as_view(), name='product_card'),
    path('test_view/', TestTemplateView.as_view(), name='test_view'),
    path('article/<int:pk>', ArticleView.as_view(), name='article'),
    path('test/', test_view, name='test'),
    path('search/', SearchView.as_view(), name='search'),
]

django-docker/website_store/order/urls.py
from django.urls import path
from order.views import BasketView, FormPayView, OrdersListView, SuccessOrderView

app_name = 'order'

urlpatterns = [
    path('form_pay/', FormPayView.as_view(), name='form_pay'),
    path('basket/', BasketView.as_view(), name='basket'),
    path('orders_list/', OrdersListView.as_view(), name='orders_list'),
    path('success_ordering/<int:order_id>', SuccessOrderView.as_view(), name='success_ordering'),
]

django-docker/website_store/website_store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mini_app/', include('mini_app.urls', namespace='mini_app')),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path('order/', include('order.urls', namespace='order')),
    path('token/', include('jwt_custom.urls', namespace='token'))
]

handler500 = 'jwt_custom.views.custom_type_error_handler'
handler404 = 'jwt_custom.views.custom_type_error_handler_404'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django-docker/website_store/order/models.py
from django.core.validators import RegexValidator
from django.db import models
from mini_app.models import Product, StoreUser


class BasketObjects(models.QuerySet):
    def total_sum(self):
        return sum([i.sum() for i in self])


class Basket(models.Model):
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    user = models.BigIntegerField()
    quantity = models.SmallIntegerField()

    objects = BasketObjects.as_manager()

    def __str__(self):
        return self.product.name

    def sum(self):
        return self.product.price * self.quantity

    def de_json(self):
        basket_item = {
            'product_name': self.product.name,
            'quantity': self.quantity,
            'price': float(self.product.price),
            'total_sum': float(self.sum())
        }
        return basket_item


class Order(models.Model):
    CREATED = 0
    PAID = 1
    STATUS_CODE = (
        (CREATED, 'Coздан'),
        (PAID, 'Оплачен'),
    )

    PAY_ONLINE = 0
    PAY_MANAGER = 1
    PAY_CODE = (
        (PAY_ONLINE, 'Оплата Онлайн'),
        (PAY_MANAGER, 'Оплата через менеджера'),
    )

    first_name = models.CharField('Имя', max_length=50)
    last_name = models.CharField('Фамилия', max_length=50)
    email = models.EmailField('Email')
    phone = models.CharField('Телефон', max_length=20, validators=[
        RegexValidator(
            regex=r'^\+?1?\d{9,15}$',
            message="Формат: '+999999999'. До 15 цифр."
        )
    ])
    address = models.CharField('Адрес', max_length=250)
    city = models.CharField('Город', max_length=100)
    created = models.DateTimeField('Создан', auto_now_add=True)
    initiator = models.ForeignKey(to=StoreUser, on_delete=models.CASCADE)
    basket_history = models.JSONField(default=dict)
    status = models.SmallIntegerField(default=CREATED, choices=STATUS_CODE)
    pay_type = models.SmallIntegerField(choices=PAY_CODE)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return f'Заказ {self.id}, {self.created}'

    def update_after_pay(self):
        """
        Удаляем данные из корзины пользователя после оплаты
        :return:
        """
        baskets = Basket.objects.filter(user=self.initiator.telegram_id)
        self.status = self.PAID
        baskets.delete()
        self.save()

    def update_payment_basket_history(self):
        """
        Добавляем данные из корзины, который пользователь выбрал
        перед оплатой
        :return:
        """
        baskets = Basket.objects.filter(user=self.initiator.telegram_id)
        self.basket_history = {
            'purchased_items': [item.de_json() for item in baskets],
            'total_sum': float(baskets.total_sum())
        }
        self.save()

    def save(
        self,
        *args,
        force_insert=False,
        force_update=False,
        using=None,
        update_fields=None,
    ):
        baskets = Basket.objects.filter(user=self.initiator.telegram_id)
        self.basket_history = {
            'purchased_items': [item.de_json() for item in baskets],
            'total_sum': float(baskets.total_sum())
        }
        super().save(
        *args,
        force_insert=False,
        force_update=False,
        using=None,
        update_fields=None,)

django-docker/website_store/order/forms.py
from django import forms
from django.core.exceptions import ValidationError
from order.models import Order


class OrderCreateForm(forms.ModelForm):
    online_payment = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    callback_request = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'phone', 'address', 'city']
        widgets = {
            'phone': forms.TextInput(attrs={
                'placeholder': '+7 (999) 123-45-67'
            }),
        }

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if not all(c in '0123456789+()- ' or c.isalpha() for c in phone):
            raise ValidationError("Недопустимые символы в номере")
        phone = (phone.replace('+', '')
                 .replace('(', '')
                 .replace(')', '')
                 .replace('-', '').
                 replace(' ', ''))
        if len(phone) != 11:  # Проверка длины
            raise ValidationError("Длина номера должна быть 11")
        return phone

django-docker/website_store/order/views.py
from django.core.cache import cache
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from jwt_custom.service import JWTAuthorization
from mini_app.models import StoreUser
from mini_app.redis import download_product_all_redis
from mini_app.tasks import send_data_ordering_telegram_bot
from order.forms import OrderCreateForm
from order.models import Basket, Order


class FormPayView(JWTAuthorization, CreateView):
    model = Order
    template_name = 'order/form_pay.html'
    form_class = OrderCreateForm

    def get_success_url(self):
        return reverse('order:success_ordering', kwargs={'order_id': self.object.id})

    def form_valid(self, form):
        user_telegram = StoreUser.objects.get(telegram_id=self.telegram_id)
        # формирует читабельные данные и отправляет в rabbitmq
        self.create_message_for_telegram(form.cleaned_data.copy(), user_telegram)

        online_payment = form.cleaned_data['online_payment']  # 1 или 0
        callback_request = form.cleaned_data['callback_request']

        if online_payment or not callback_request:
            form.instance.pay_type = 0
        elif not online_payment or callback_request:
            form.instance.pay_type = 1
        else:
            # Обработка ошибки
            print(online_payment, callback_request,
                  'online_payment, callback_request', form.cleaned_data)
            form.instance.pay_type = 0
            raise ValueError()
        form.instance.initiator = user_telegram
        response = super().form_valid(form)
        return response

    def create_message_for_telegram(self, form_data: dict, user_telegram: StoreUser):
        send_data_tg = form_data
        basket_user = [item.de_json() for item in Basket.objects.filter(user=self.telegram_id)]

        text_basket_user = ''
        for product in basket_user:
            text_basket_user += '\n\nТовар:\n'
            for key, value in product.items():
                text_basket_user += f'{key}: {value}\n'

        send_data_tg.update(
            {
                'telegram_ID': self.telegram_id,
                'telegram_username': user_telegram.telegram_username,
                'telegram_first_name': user_telegram.telegram_first_name,
                'telegram_last_name': user_telegram.telegram_last_name,
                'Заказы': text_basket_user
            }
        )
        send_data_ordering_telegram_bot(send_data_tg)


class OrdersListView(JWTAuthorization, ListView):
    template_name = 'order/orders.html'
    queryset = Order.objects.all()
    ordering = ('-id',)
    context_object_name = 'basket_history'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(initiator=StoreUser.objects.get(telegram_id=self.telegram_id))


class OrderDetailView(DetailView):
    template_name = 'orders/order.html'
    model = Order

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['id'] = self.object.id
        return context


@method_decorator(csrf_exempt, name='dispatch')
class BasketView(JWTAuthorization, TemplateView):
    template_name = 'order/basket.html'

    def get_context_data(self, **kwargs):
        user = self.telegram_id
        context = super().get_context_data(**kwargs)
        list_id_product = Basket.objects.filter(user=user).values_list('product_id', 'quantity')
        list_product = []
        for item in list_id_product:
            product_id, product_quantity = str(item[0]), item[1]
            product = cache.get('products').get(product_id)
            product.update({'quantity': product_quantity, 'sum': product['price'] * product_quantity})
            list_product.append(product)
        context['products'] = list_product
        context['total_sum'] = self.get_total_sum(list_product)
        return context

    def get_total_sum(self, list_product: list):
        total_sum = 0
        for product in list_product:
            total_sum += product['price'] * product['quantity']
        return total_sum


class SuccessOrderView(TemplateView):
    template_name = 'order/success_ordering.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        order_id = self.kwargs.get('order_id')
        context['order_id'] = order_id
        return context

django-docker/website_store/order/templates/order/basket.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Корзина Wildberries</title>
    <link rel="stylesheet" href="{% static 'mini_app/css/index/hat.css' %}" />
    <link rel="stylesheet" href="{% static 'order/css/basket.css' %}" />
    <script src="{% static 'order/js/basket.js' %}"></script>

    <script src="https://cdn.jsdelivr.net/npm/axios@1.6.7/dist/axios.min.js"></script>

</head>
<body>
    <div>
        {% include 'mini_app/header.html' %}
    </div>

    <div class="container">
        <div class="header">
            <a href="#" class="back-btn">←</a>
            <h1 class="title">Корзина</h1>
        </div>

        <div id="cart-items">
            {% for product in products %}
            <div class="cart-item">
                <div class="item-content">
                    <!-- Новый контейнер -->
                    <a href="{% url 'mini_app:product_card' product.id %}">
                        <img src="{{ product.images_product.0 }}" class="item-image" alt="{{ product.name }}">
                    </a>
                    <div class="item-info">
                        <input type="hidden" class="price_product" value="{{ product.price }}" />
                        <div class="item-price">{{ product.sum }} ₽</div>
                        <div class="item-title">{{ product.name }}</div>
                        <div class="quantity-controls">
                            <button class="quantity-btn minus" data-id="{{ product.id }}">-</button>
                            <span class="quantity">{{ product.quantity }}</span>
                            <button class="quantity-btn plus" data-id="{{ product.id }}">+</button>
                        </div>
                    </div>
                </div>
                <button class="delete-btn" data-id="{{ product.id }}">×</button>
            </div>
            {% endfor %}
        </div>

        <div class="total">
            <div class="total-content">
                {% if products %}
                <span class="total-text">Итого:</span>
                <span class="total-price">{{ total_sum }} ₽</span>
                {% else %}

                {% endif %}
            </div>
            {% if products %}
            <a href="{% url 'order:form_pay' %}" class="a-checkout-btn">
                <button href="http://google.com" class="checkout-btn">Перейти к оформлению</button>
            </a>
            {% else %}

            <a href="{% url 'mini_app:main_menu' %}" class="a-checkout-btn">
                <button href="http://google.com" class="checkout-btn">Перейти к каталогу товаров</button>
            </a>
            {% endif %}
        </div>
        {% if not products %}
        <div id="empty-cart-message" class="empty-cart">
            Ваша корзина пуста
        </div>
        {% endif %}
        <div id="empty-cart-message" class="empty-cart" style="display: none;">
            Ваша корзина пуста
        </div>
    </div>
</body>
</html>

django-docker/website_store/order/templates/order/form_pay.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Оформление заказа</title>

    <link rel="stylesheet" href="{% static 'mini_app/css/index/hat.css' %}" />
    <link rel="stylesheet" href="{% static 'order/css/form_pay.css' %}">
    <script src="{% static 'order/js/form_pay.js' %}"></script>
</head>
<body>
    {% include 'mini_app/header.html' %}
    <div class="checkout-container">
        <form action="{% url 'order:form_pay' %}" method="post" id="checkoutForm">
            {% csrf_token %}

            <!-- Секция контактной информации -->
            <div class="form-section">
                <h2 class="section-title">Контактная информация</h2>
                <div class="row">
                    <div class="input-group">
                        {{ form.first_name.label_tag }}
                        {{ form.first_name }}
                        {{ form.first_name.errors }}
                    </div>
                    <div class="input-group">
                        {{ form.last_name.label_tag }}
                        {{ form.last_name }}
                        {{ form.last_name.errors }}
                    </div>
                </div>

                <div class="input-group">
                    {{ form.email.label_tag }}
                    {{ form.email }}
                    {{ form.email.errors }}
                </div>

                <div class="input-group">
                    {{ form.phone.label_tag }}
                    {{ form.phone }}
                    {{ form.phone.errors }}
                </div>
            </div>
                <input type="hidden" name="online_payment" id="online_payment" value="0">
                <input type="hidden" name="callback_request" id="callback_request" value="0">
            <!-- Секция адреса доставки -->
            <div class="form-section">
                <h2 class="section-title">Адрес доставки</h2>
                <div class="input-group">
                    {{ form.address.label_tag }}
                    {{ form.address }}
                    {{ form.address.errors }}
                </div>

                <div class="row">
                    <div class="input-group">
                        {{ form.city.label_tag }}
                        {{ form.city }}
                        {{ form.city.errors }}
                    </div>
                </div>
            </div>

            <!-- Секция способа оплаты -->
            <div class="form-section">
                <h2 class="section-title">Способ оплаты</h2>
                <div class="row">
                    <div class="input-group">
                        <button type="button" class="method-btn" onclick="togglePaymentMethod('callback')">
                            ☎️ Связаться для оформления
                        </button>
                    </div>
<!--                    <div class="input-group">-->
<!--                        <button type="button" class="method-btn" onclick="togglePaymentMethod('online')">-->
<!--                            💳 Оплатить онлайн-->
<!--                        </button>-->
<!--                    </div>-->
                </div>

                <!-- Поле для обратного звонка -->
                <div class="input-group" id="callback-field" style="display: none;">

                </div>

                <!-- Блок с методами онлайн-оплаты -->
                <div class="payment-options" id="online-methods" style="display: none;">

                </div>
            </div>

            <button type="submit" class="btn-submit">Оформить заказ</button>
        </form>
    </div>
</body>
</html>

django-docker/website_store/order/templates/order/order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

django-docker/website_store/order/templates/order/orders.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'order/css/orders.css' %}">
    <style>
* {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
}

body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    line-height: 1.6;
    color: #2d3436;
    background-color: #f8f9fa;
    min-height: 100vh;
}

.container {
    width: 100%;
    max-width: 100%;
    padding: 1.5rem 1rem;
    margin: 0 auto;
}

.text-center {
    text-align: center;
}

.mt-3 { margin-top: 1.5rem; }
.mt-5 { margin-top: 3rem; }
.pt-5 { padding-top: 3rem; }

/* Orders table styles */
.orders {
    background: white;
    border-radius: 12px;
    box-shadow: 0 4px 6px rgba(0,0,0,0.05);
    overflow-x: auto;
    padding: 1rem;
}

.table {
    width: 100%;
    border-collapse: collapse;
    font-size: 1rem;
    min-width: 600px;
}

.table th,
.table td {
    padding: 1.25rem;
    text-align: left;
    border-bottom: 2px solid #f1f2f6;
    vertical-align: top;
}

.table th {
    background-color: #fff;
    font-weight: 600;
    color: #2d3436;
    font-size: 1.1rem;
}

.table tr:last-child td {
    border-bottom: none;
}

/* Total price */
.total-price {
    font-size: 1.4rem;
    font-weight: 700;
    color: #2d3436;
    margin-top: 2rem;
    padding: 1rem;
    background: #fff;
    border-radius: 8px;
    display: flex;
    justify-content: flex-end;
    gap: 1rem;
}

/* Mobile styles */
@media (max-width: 768px) {
    .container {
        padding: 1rem;
    }

    .orders {
        padding: 0;
        border-radius: 0;
        box-shadow: none;
        background: transparent;
    }

    .table {
        min-width: 100%;
        font-size: 1rem;
        display: block;
    }

    .table thead {
        display: none;
    }

    .table tr {
        display: flex;
        flex-direction: column;
        margin-bottom: 1.5rem;
        background: white;
        border-radius: 12px;
        box-shadow: 0 2px 8px rgba(0,0,0,0.08);
        padding: 1rem;
    }

    .table td {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 1rem;
        border-bottom: 1px solid #eee;
    }

    .table td:last-child {
        border-bottom: none;
    }

    .table td::before {
        content: attr(data-label);
        font-weight: 600;
        color: #636e72;
        margin-right: 1.5rem;
        flex-shrink: 0;
    }

    .total-price {
        font-size: 1.2rem;
        flex-direction: column;
        align-items: flex-end;
        background: transparent;
        padding: 0;
    }
}

@media (max-width: 480px) {
    .table td {
        padding: 0.75rem;
        font-size: 1rem;
    }

    .table td::before {
        font-size: 0.95rem;
    }

    body {
        font-size: 16px;
    }

    .total-price {
        font-size: 1.1rem;
    }
}

/* Typography enhancements */
td {
    font-size: 1.05rem;
    color: #2d3436;
}

th {
    letter-spacing: 0.5px;
}
    </style>
</head>
<body>
 <section>
    <div class="container pt-5">
        <div class="text-center mt-5">
            <div class="orders mt-5">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Номер заказа №</th>
                        <th scope="col">Cтатус</th>
                        <th scope="col">Создан</th>
                        <th scope="col">Сумма</th>
                    </tr>
                    </thead>

<tbody>
{% for item in basket_history %}
    <tr>
        <td data-label="Номер заказа №">{{ item.id }}</td>
        <td data-label="Cтатус">{{ item.get_status_display }}</td>
        <td data-label="Создан">{{ item.created }}</td>
        <td data-label="Сумма">{{ item.basket_history.total_sum }} руб.</td>
    </tr>
{% endfor %}
</tbody>

                </table>
                <p class="float-right h4 mt-3">Итого {{ basket_history.total_sum }} руб.</p>
            </div>
        </div>
    </div>
</section>
</body>
</html>

django-docker/website_store/order/templates/order/success_ordering.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8" />
    <title>Перезапустите приложение</title>
    <script src="https://telegram.org/js/telegram-web-app.js"></script>
    <style>
        body {
            font-family: Arial, sans-serif;
            background: #f9f9f9;
            color: #333;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
            margin: 0;
            text-align: center;
        }
        .container {
            background: #fff;
            padding: 30px 40px;
            border-radius: 12px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.1);
            max-width: 400px;
        }
        h1 {
            color: #0088cc;
            margin-bottom: 20px;
        }
        p {
            font-size: 18px;
            margin-bottom: 30px;
        }
        button {
            background-color: #0088cc;
            color: white;
            border: none;
            padding: 12px 24px;
            font-size: 16px;
            border-radius: 8px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }
        button:hover {
            background-color: #006699;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Заказ успешно сформирован</h1>
      <p>Номер заказа №{{ order_id }}</p>
        <p>Скоро с вами свяжется менеджер для уточнения деталей заказа</p>
            <p>Вы можете вернуться на главное меню по кнопке ниже</p>
        <a href="https://shovik.ru/mini_app/menu/">
  <button type="button">Главное меню</button>
</a>
    </div>
</body>
</html>