django-docker/website_store/jwt_custom/urls.py
from django.urls import path
from jwt_custom.views import ErrorAuthorizationView, set_cookie_view

app_name = 'token_jwt'

urlpatterns = [
    path('get/', set_cookie_view, name='get'),
    path('error/', ErrorAuthorizationView.as_view(), name='error_authorization'),
]

django-docker/website_store/mini_app/urls.py
from django.urls import path
from mini_app.views import (ArticleView, MainMenuView, ProductCardView,
                            SearchView, TestTemplateView, test_view)

app_name = 'mini_app'

urlpatterns = [
    path('menu/', MainMenuView.as_view() , name='main_menu'),
    path('menu/<str:param>/', MainMenuView.as_view(), name='main_menu_with_param'),
    path('product/<str:product_id>', ProductCardView.as_view(), name='product_card'),
    path('test_view/', TestTemplateView.as_view(), name='test_view'),
    path('article/<int:pk>', ArticleView.as_view(), name='article'),
    path('test/', test_view, name='test'),
    path('search/', SearchView.as_view(), name='search'),
]

django-docker/website_store/order/urls.py
from django.urls import path
from order.views import BasketView, FormPayView, OrdersListView, SuccessOrderView

app_name = 'order'

urlpatterns = [
    path('form_pay/', FormPayView.as_view(), name='form_pay'),
    path('basket/', BasketView.as_view(), name='basket'),
    path('orders_list/', OrdersListView.as_view(), name='orders_list'),
    path('success_ordering/<int:order_id>', SuccessOrderView.as_view(), name='success_ordering'),
]

django-docker/website_store/website_store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mini_app/', include('mini_app.urls', namespace='mini_app')),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path('order/', include('order.urls', namespace='order')),
    path('token/', include('jwt_custom.urls', namespace='token'))
]

handler500 = 'jwt_custom.views.custom_type_error_handler'
handler404 = 'jwt_custom.views.custom_type_error_handler_404'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django-docker/website_store/mini_app/models.py
import uuid
from io import BytesIO

from django.core.files import File
from django.db import models
from django_ckeditor_5.fields import CKEditor5Field
from PIL import Image


class StoreUser(models.Model):
    telegram_id = models.BigIntegerField(unique=True)
    telegram_username = models.CharField()
    telegram_first_name = models.CharField(null=True, blank=True)
    telegram_last_name = models.CharField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)


class Country(models.Model):
    country = models.CharField(max_length=256)

    def __str__(self):
        return self.country


class SubcategoryProduct(models.Model):
    subcategory_product = models.CharField(max_length=256)

    def __str__(self):
        return self.subcategory_product


class TypeEquipment(models.Model):
    type_equipment = models.CharField(max_length=256)

    def __str__(self):
        return self.type_equipment


class Brand(models.Model):
    brand = models.CharField(max_length=256)

    def __str__(self):
        return f"{self.id} {self.brand}"


class Product(models.Model):
    """
    Установить CASCADE в on_delete
    """
    name = models.CharField(max_length=256)
    description = models.CharField()
    brand = models.ForeignKey(to=Brand, on_delete=models.DO_NOTHING)
    view_main_menu = models.BooleanField(default=False)
    price = models.IntegerField()
    cooling_power = models.FloatField()
    heating_power = models.FloatField()
    working_area = models.FloatField()
    sound_level = models.FloatField()
    country = models.ForeignKey(to=Country, on_delete=models.DO_NOTHING)
    group_product = models.ForeignKey(to=SubcategoryProduct, on_delete=models.DO_NOTHING)
    type_equipment = models.ForeignKey(to=TypeEquipment, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.name


class ProductImage(models.Model):
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,  # Удалять изображения при удалении товара
        related_name='images'
    )
    image = models.ImageField(
        upload_to='products_images/',  # Папка для загрузки
        verbose_name='Изображение'
    )

    def generate_unique_name(self):
        return f"{uuid.uuid4().hex}.webp"

    def compress(self, image):
        img = Image.open(image)
        if img.mode in ('RGBA', 'P'):
            img = img.convert('RGB')
        im_io = BytesIO()
        img.save(im_io, 'WEBP', quality=70, method=6)
        return File(im_io, name=image.name)

    def save(
        self,
        *args,
        force_insert=False,
        force_update=False,
        using=None,
        update_fields=None,
    ):
        if self.image:  # Только если есть изображение
            # Генерация уникального имени перед сохранением
            original_name = self.image.name
            print('original_name', original_name, '\n\n')
            self.image.name = self.generate_unique_name()
            # Сжатие и оптимизация изображения
            compressed_image = self.compress(self.image)
            self.image.save(
                compressed_image.name,
                compressed_image.file,
                save=False
            )

        super().save(
      *args,
            force_insert=False,
            force_update=False,
            using=None,
            update_fields=None,
        )

    def __str__(self):
        return self.product.name


class ParameterProduct(models.Model):
    key = models.CharField(max_length=256)
    value = models.CharField()
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)

    def __str__(self):
        return self.key


class ReviewProduct(models.Model):
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    user_review_name = models.CharField()
    comment = models.CharField()
    rating = models.SmallIntegerField()


class Article(models.Model):
    title = models.CharField(max_length=200, verbose_name="Заголовок")
    image = models.ImageField(upload_to='article/', verbose_name='Изображение статьи')
    content = CKEditor5Field(verbose_name='Полное описание', config_name='extends')
    show_counter = models.IntegerField(verbose_name='Счетчик показов статьи', null=True)

    def __str__(self):
        return self.title

django-docker/website_store/mini_app/forms.py
from django import forms
from django.core.cache import cache
from mini_app.redis import check_data_in_redis

def get_cache_param(key: str):
    data = cache.get(key)
    if data is None:
        print('\n\n')
        print('ключа нет')
        print('\n\n')
        check_data_in_redis()
        print(cache.get(key))
        print('\n\n')
        return cache.get(key)
    else:
        return data

class SearchForm(forms.Form):
    brand = forms.ChoiceField(
        choices=get_cache_param('brand_list'),
        required=False,
    )
    country = forms.ChoiceField(
        choices=get_cache_param('country_list'),
        required=False
    )
    type_equipment = forms.ChoiceField(
        choices=get_cache_param('typeEquipment'),
        required=False
    )

    price__lt = forms.IntegerField(widget=forms.NumberInput(attrs={
                                                                "class": 'price-input',
                                                                'placeholder': 'До',
                                                                'type': 'number',
                                                                'value': ''
                                                                }
                                                            ),
                                  required=False)
    price__gt = forms.IntegerField(widget=forms.NumberInput(attrs={
                                                                "class": 'price-input',
                                                                'placeholder': 'От',
                                                                'type': 'number'
                                                                    }
                                                            ),
                                  required=False)

    cooling_power__gt = forms.IntegerField(widget=forms.NumberInput(attrs={
                                                                        "class": 'price-input',
                                                                        'placeholder': 'От',
                                                                        'type': 'number'}
                                                                    ),
                                   required=False)
    cooling_power__lt = forms.IntegerField(widget=forms.NumberInput(attrs={
                                                                        "class": 'price-input',
                                                                        'placeholder': 'До',
                                                                        'type': 'number'}
                                                                    ),
                                           required=False)
    heating_power__gt = forms.IntegerField(widget=forms.NumberInput(attrs={
                                                                        "class": 'price-input',
                                                                        'placeholder': 'От',
                                                                        'type': 'number'}
                                                                    ),
                                           required=False)
    heating_power__lt = forms.IntegerField(widget=forms.NumberInput(attrs={
                                                                        "class": 'price-input',
                                                                        'placeholder': 'До',
                                                                        'type': 'number'}
                                                                    ),
                                           required=False)
    working_area__gt = forms.IntegerField(widget=forms.NumberInput(attrs={
                                                                        "class": 'price-input',
                                                                        'placeholder': 'От',
                                                                        'type': 'number'}
                                                                    ),
                                           required=False)
    working_area__lt = forms.IntegerField(widget=forms.NumberInput(attrs={
                                                                        "class": 'price-input',
                                                                        'placeholder': 'До',
                                                                        'type': 'number'}
                                                                    ),
                                           required=False)
    sound_level__gt = forms.IntegerField(widget=forms.NumberInput(attrs={
                                                                        "class": 'price-input',
                                                                        'placeholder': 'От',
                                                                        'type': 'number'}
                                                                    ),
                                          required=False)
    sound_level__lt = forms.IntegerField(widget=forms.NumberInput(attrs={
                                                                        "class": 'price-input',
                                                                        'placeholder': 'До',
                                                                        'type': 'number'}
                                                                    ),
                                          required=False)

django-docker/website_store/mini_app/views.py
from django.core.cache import cache
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from mini_app.filter import ProductSearch
from mini_app.forms import SearchForm
from mini_app.models import Article, Product
from mini_app.redis import download_product_all_redis, search_parameters_redis, check_data_in_redis

F = 'test_fastapi'


@csrf_exempt
def test_view(request):
    pass


class TestTemplateView(TemplateView):
    template_name = f'mini_app/{F}.html'


class MainMenuView(ListView):
    template_name = 'mini_app/index.html'
    paginate_by = 4

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.kwargs.get('param', False):
            if self.kwargs.get('param') == 'ShowPopup':
                context['showPopup'] = True
        return context

    def get_queryset(self):
        check_data_in_redis()
        return list(cache.get('products').values())


class ProductCardView(TemplateView):
    template_name = 'mini_app/product_card.html'

    def get_context_data(self, **kwargs):
        check_data_in_redis()
        context = super().get_context_data(**kwargs)
        product_id = self.kwargs.get('product_id')
        context['product_card'] = cache.get('products').get(product_id)
        return context


class ArticleView(DetailView):
    template_name = 'mini_app/article.html'
    model = Article

    # Здесь добавить аналитику

class SearchView(ListView):
    template_name = 'mini_app/search.html'
    model = Product
    paginate_by = 6
    form = SearchForm
    filterset_class = ProductSearch
    context_object_name = 'product_list'

    def get_queryset(self):
        qs = super().get_queryset()
        data_request = self.update_get_data(dict(self.request.GET))
        self.data_request = data_request
        self.filterset = self.filterset_class(
            data=data_request,
            queryset=qs
        )
        if not self.filterset.is_valid():
            print("ОШИБКИ ФИЛЬТРАЦИИ:", self.filterset.errors)
        return self.filterset.qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = SearchForm(initial=self.data_request)
        return context

    def update_get_data(self, request_get) -> dict:
        """
        'brand': ['Ballu'], 'country': ['']
        ->
        {'brand': 'Ballu', 'price__lt': '1616'}
        Нормализуем данные, удаляем пустые значения, value=list -> value->str
        :param request_get: self.request.GET or request.GET
        :return: dict
        """
        iterable_dict = dict(request_get)
        dict_data = {}
        for key, value in iterable_dict.items():
            if not value[0]:
                continue
            dict_data.update({key: value[0]})
        return dict_data

django-docker/website_store/mini_app/templates/mini_app/header.html
{% load static %}

<div class="hat">
    <div class="main-icon">
        <a href="{% url 'mini_app:main_menu' %}" target="_self">
            <img src="{% static 'mini_app/icon/main-icon.svg' %}" alt="main-icon" class="main-icon-image">
        </a>
    </div>

    <div class="basket-icon">
        <a href="{% url 'order:basket' %}" >

            <img src="{% static 'mini_app/icon/basket.svg' %}" alt="basket-icon" class="basket-icon-image">
        </a>
    </div>

    <div class="channel-button">
        <a href="javascript:Telegram.WebApp.openTelegramLink('https://t.me/shoviki');" target="_self">
            <img src="{% static 'mini_app/icon/channle_button.png' %}" alt="channle-button" class="channel-button-image">
        </a>
    </div>
</div>

<script>
    window.API_URLS = {
        getToken: "{% url 'token:get' %}"
    };

    window.ERROR = {
        error_authorization: "{% url 'token:error_authorization' %}"
    }
  window.URL_SITE = {
    main_page: "{% url 'mini_app:main_menu' %}",
    basket: "{% url 'order:basket' %}",
    form_pay: "{% url 'order:form_pay' %}",
    product: "{% url 'mini_app:product_card' 0 %}"
  };
    window.URL_FASTAPI = {
        url: 'https://shovik.ru/api'
    };
    Telegram.WebApp.ready();
    const WebApp = window.Telegram.WebApp;

        window.INIT_DATA = {
        initData: WebApp.initData
<!--        initData: 'query_id=AAHdF6IQAAAAAN0XohDhrOr8&user=%7B%22id%22%3A279058397%2C%22first_name%22%3A%22John%22%2C%22last_name%22%3A%22Doe%22%2C%22username%22%3A%22johndoe%22%2C%22language_code%22%3A%22en%22%7D&auth_date=1653041776&hash=c501b8e0a6b38d4e9e9a82ae8816f0a9d8a9c9e0e6a9e6a9e6a9e6a9e6a9e6a9'-->
    };
</script>

django-docker/website_store/mini_app/templates/mini_app/index.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SHOVIK STORE Bot</title>
    <link rel="stylesheet" href="{% static 'mini_app/css/index/index.css' %}" />
    <link rel="stylesheet" href="{% static 'mini_app/css/index/scroll.css' %}" />
    <link rel="stylesheet" href="{% static 'mini_app/css/index/search.css' %}" />
    <link rel="stylesheet" href="{% static 'mini_app/css/index/product_list_page.css' %}" />
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
    <link rel="stylesheet" href="{% static 'mini_app/css/index/hat.css' %}" />
    <link rel="stylesheet" href="{% static 'mini_app/css/index/button_basket.css' %}" />
    <script src="{% static 'mini_app/js/index/index.js' %}"></script>
    <script src="{% static 'mini_app/js/index/scroll.js' %}"></script>
    <script src="{% static 'auth/js/auth.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios@1.6.7/dist/axios.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@500;600&family=Space+Grotesk:wght@500&display=swap" rel="stylesheet">

    <script src="https://telegram.org/js/telegram-web-app.js"></script>
</head>
<body>

    {% include 'mini_app/header.html' %}
    <form method="get" action="{% url 'mini_app:search' %}" id="searchForm">
        {% csrf_token %}
    <div class="search-container">
        <div class="search-box">
            <input type="text"
                   class="search-input"
                   placeholder="Введите поисковый запрос..."
                   id="searchInput"
                   name="q"
                   value="{{ request.GET.q }}"
            >
            <button type="submit" class="search-btn" id="searchBtn">
                <i class="fas fa-search"></i>
            </button>
            <div class="search-results" id="searchResults"></div>
        </div>
    </div>
    </form>

    <div class="scroll-container">
        <div class="blocks-wrapper">
            <a href="{% url 'mini_app:search' %}?view_main_menu=True" class="block">Популярное</a>
            <a href="{% url 'mini_app:search' %}?brand=Ballu" class="block">Ballu</a>
            <a href="{% url 'order:orders_list' %}" class="block">Orders</a>
            <a href="{% url 'mini_app:search' %}?brand=Electrolux" class="block">Elecrolux</a>
            <a href="{% url 'mini_app:search' %}?brand=Toshiba" class="block">Toshiba</a>
            <a href="{% url 'mini_app:search' %}?brand=Energolux" class="block">Energolux</a>
            <a href="{% url 'mini_app:search' %}?brand=ECOCLIMA" class="block">ECOCLIMA</a>
        </div>
    </div>

    <div class="scroll-container-image">
        <div class="blocks-wrapper-image">
            <a href="{% url 'mini_app:article' 1 %}" class="block-image">
                <img src="{% static 'mini_app/icon/slide1.png' %}" class="block-image">
            </a>
            <a href="{% url 'mini_app:article' 3 %}" class="block-image">
                <img src="{% static 'mini_app/icon/slide2.png' %}" class="block-image">
            </a>
            <a href="{% url 'mini_app:article' 4 %}" class="block-image">
                <img src="{% static 'mini_app/icon/slide3.png' %}" class="block-image">
            </a>
            <a href="{% url 'mini_app:article' 5 %}" class="block-image">
                <img src="{% static 'mini_app/icon/slide4.png' %}" class="block-image">
            </a>
            <a href="{% url 'mini_app:article' 6 %}" class="block-image">
                <img src="{% static 'mini_app/icon/slide5.png' %}" class="block-image">
            </a>
        </div>
    </div>

    <div class="products-grid" id="productsContainer">
        {% for product in object_list %}
        <div class="product-card">

            <div class="swiper product-swiper">
            <div class="swiper-wrapper">
                {% for image in product.images_product %}
                <div class="swiper-slide">
                    <a href="{% url 'mini_app:product_card' product.id %}" class="product-image">
                        <img src="{{ image }}" alt="{{ product.name }}" class="product-image">
                    </a>
                </div>
                {% endfor %}
            </div>
            <!-- Пагинация и навигация -->
            <div class="swiper-pagination"></div>
            </div>
            <a href="{% url 'mini_app:product_card' product.id %}" class="product-link">
                <h3 class="product-title">{{ product.name }}</h3>
            </a>
            <div class="brand">{{ product.brand.brand }}</div>
            <div class="price-container">

                <span class="new-price">{{ product.price }} руб.</span>
            </div>
            <div class="stock-status">В наличии</div>
            <!-- class="id_product" здесь добавляется значение ID товара  -->
            <input type="hidden" class="id_product" value="{{ product.id }}" />

                <button id="button{{ product.id }}" class="add-to-cart" onclick="onclick">В корзину</button>
        </div>
        {% endfor %}
    </div>
{% include 'mini_app/footer.html' %}
<script>
    {% if showPopup %}
    alert('Все норм для повторной авторизации))')
    Telegram.WebApp.showAlert('Вы попали на эту страницу, для повторной авторизации. С уважением, команда разработки');
    {% endif %}
</script>

    <script>
  document.addEventListener('DOMContentLoaded', function () {
    // Инициализация всех слайдеров с классом .product-swiper
    const swipers = document.querySelectorAll('.product-swiper');
    swipers.forEach(swiperEl => {
      new Swiper(swiperEl, {
        loop: true,
        pagination: {
          el: swiperEl.querySelector('.swiper-pagination'),
          clickable: true,
        },
        slidesPerView: 1,
        spaceBetween: 10,
      });
    });
  });
</script>
</body>
</html>

django-docker/website_store/mini_app/templates/mini_app/search.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Поиск товаров</title>
    <link rel="stylesheet" href="{% static 'mini_app/css/search/search.css' %}">
    <link rel="stylesheet" href="{% static 'mini_app/css/index/hat.css' %}" />
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
    <link rel="stylesheet" href="{% static 'mini_app/css/index/product_list_page.css' %}" />
    <link rel="stylesheet" href="{% static 'mini_app/css/index/button_basket.css' %}" />
    <script src="{% static 'mini_app/js/index/index.js' %}"></script>

</head>
<body>

    {% include 'mini_app/header.html' %}

 <form action="{% url 'mini_app:search' %}" method="get" id="searchView">
    <div class="search-container">
                {% csrf_token %}
            <div class="filter-group">
                <label class="filter-label">Бренд кондиционера:</label>
                <div class="select-wrapper">
                    {{ form.brand }}
                </div>
            </div>

            <div class="filter-group">
                <label class="filter-label">Страна производитель:</label>
                <div class="select-wrapper">
                    {{ form.country }}
                </div>
            </div>

            <div class="filter-group">
                <label class="filter-label">Тип оборудования:</label>
                <div class="select-wrapper">
                        {{ form.type_equipment }}
                </div>
            </div>

            <!-- Диапазон цен -->
            <div class="filter-group">
                <label class="filter-label">Цена, ₽</label>
                <div class="price-range">
                    {{ form.price__gt }} {{ form.price__lt }}
                </div>
            </div>
            <!-- Мощность охлаждения -->
            <div class="filter-group">
                <label class="filter-label">Мощность охлаждения:</label>
                <div class="price-range">
                    {{ form.cooling_power__gt }} {{ form.cooling_power__lt }}
                </div>
            </div>
            <!-- Мощность обогрева -->
            <div class="filter-group">
                <label class="filter-label">Мощность обогрева: </label>
                <div class="price-range">
                    {{ form.heating_power__gt }} {{ form.heating_power__lt }}
                </div>
            </div>
            <!-- Рабочая площадь -->
            <div class="filter-group">
                <label class="filter-label">Рабочая площадь: </label>
                <div class="price-range">
                    {{ form.working_area__gt }} {{ form.working_area__lt }}
                </div>
            </div>
            <!-- Уровень шума -->
            <div class="filter-group">
                <label class="filter-label">Уровень шума: </label>
                <div class="price-range">
                    {{ form.sound_level__gt }} {{ form.sound_level__lt }}
                </div>
            </div>
        </div>

        <button type="submit" class="apply-button">Показать результаты</button>
    </div>
</form>
    {% if product_list %}
    <div class="products-grid" id="productsContainer">
        {% for product in product_list %}
        <div class="product-card">

            <div class="swiper product-swiper">
            <div class="swiper-wrapper">
                {% for image in product.images.all %}
                <div class="swiper-slide">
                    <a href="{% url 'mini_app:product_card' product.id %}" class="product-image">
                        <img src="{{ image.image.url }}" alt="{{ product.name }}" class="product-image">
                    </a>
                </div>
                {% endfor %}
            </div>
            <!-- Пагинация и навигация -->
            <div class="swiper-pagination"></div>
            </div>
            <a href="{% url 'mini_app:product_card' product.id %}" class="product-link">
                <h3 class="product-title">{{ product.name }}</h3>
            </a>
            <div class="brand">{{ product.brand.brand }}</div>
            <div class="price-container">

                <span class="new-price">{{ product.price }} руб.</span>
            </div>
            <div class="stock-status">В наличии</div>
            <!-- class="id_product" здесь добавляется значение ID товара  -->
            <input type="hidden" class="id_product" value="{{ product.id }}" />

                <button id="button{{ product.id }}" class="add-to-cart" onclick="onclick">В корзину</button>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <div id="empty-cart-message" class="empty-cart">
            По вашему запросу ничего не найдено
    </div>
    {% endif %}

    {% include 'mini_app/footer.html' %}
    <script>
        // Активация чипов категорий
        document.querySelectorAll('.category-chip').forEach(chip => {
            chip.addEventListener('click', function() {
                document.querySelectorAll('.category-chip').forEach(c => c.classList.remove('active'));
                this.classList.add('active');
            });
        });
    </script>
        <script>
  document.addEventListener('DOMContentLoaded', function () {
    // Инициализация всех слайдеров с классом .product-swiper
    const swipers = document.querySelectorAll('.product-swiper');
    swipers.forEach(swiperEl => {
      new Swiper(swiperEl, {
        loop: true,
        pagination: {
          el: swiperEl.querySelector('.swiper-pagination'),
          clickable: true,
        },
        slidesPerView: 1,
        spaceBetween: 10,
      });
    });
  });
</script>
</body>
</html>

django-docker/website_store/mini_app/templates/mini_app/test_fastapi.html
!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Корзина Wildberries</title>
</head>>
<body>
    {% csrf_token %}
    <button onclick="showPopup()">click me</button>
    <button onclick="showPopupToken()">click get token</button>
</body>

<script>

    function getCookie(name) {
  const value = `; ${document.cookie}`;
  const parts = value.split(`; ${name}=`);
  if (parts.length === 2) return parts.pop().split(';').shift();
}
async function showPopup() {
    try {
        const response = await fetch('http://127.0.0.1:8000/token_jwt/lol', {
            method: 'PUT',
            credentials: 'include',
            headers: {
                'Content-Type': 'application/json',
            },
            data: {dfg: 'dafga'}
        });

        if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`);
        }

        const data = await response.json();
        console.log('Response:', data);
        return data;
    } catch (error) {
        console.error('Fetch error:', error);
        throw error;
    }
}

async function showPopupToken() {
    const data = {
    initData: 'query_id=AAHdF6IQAAAAAN0XohDhrOr8&user=%7B%22id%22%3A279058397%2C%22first_name%22%3A%22John%22%2C%22last_name%22%3A%22Doe%22%2C%22username%22%3A%22johndoe%22%2C%22language_code%22%3A%22en%22%7D&auth_date=1653041776&hash=c501b8e0a6b38d4e9e9a82ae8816f0a9d8a9c9e0e6a9e6a9e6a9e6a9e6a9e6a9'
};
    try {
        const response = await fetch(
            '{% url "token:get" %}',
            {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify(data),
                credentials: 'include'
            }
        );
        console.log('Response:', await response.json());
    } catch (error) {
        console.error('Error:', error);
    }
}
</script>
</html>